[CR-16240] Fix to add OFC to credit note for cancelled shipments
Bizongo/db_trigger_handler pull request #14
Opened 2022-03-16 17:04 UTC by vinobiz

2022-03-17 10:28 UTC, abhijits requested changes

2022-03-17 10:28 UTC, abhijits commented on lib/handlers/shipment_handler.rb
> +      amount = data[:shipment]['total_buyer_invoice_amount'].to_f - data[:shipment]['total_buyer_service_charge'].to_f;
@vinobiz if this is empty or blank? 
data[:shipment]['total_buyer_invoice_amount']

2022-05-12 05:52 UTC, Vishwajith-mr commented on lib/handlers/shipment_handler.rb
> +        amount = amount + ((data[:shipment]['fulfilment_charges'].to_f.round(2) * APP_CONFIG["buyer_service_charges"]["rate"])/ 100 ).to_f.round(2);
@abbasdawoodbiz I could not get this calculation. Can you help me understand?

2022-05-12 06:25 UTC, abbasdawoodbiz commented on lib/handlers/shipment_handler.rb
> +        amount = amount + ((data[:shipment]['fulfilment_charges'].to_f.round(2) * APP_CONFIG["buyer_service_charges"]["rate"])/ 100 ).to_f.round(2);
@ishanbiz can you check if the CN created originally due to return consists of the OFC or just the tax on OFC

2022-05-12 06:26 UTC, merged

2022-05-12 08:40 UTC, ishanbiz commented on lib/handlers/shipment_handler.rb
> +        amount = amount + ((data[:shipment]['fulfilment_charges'].to_f.round(2) * APP_CONFIG["buyer_service_charges"]["rate"])/ 100 ).to_f.round(2);
@abbasdawoodbiz none of the notes today have OFC and its tax. they only contain product value with tax.